In [1]:
import numpy as np
import pandas as pd

In [8]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product':['A','B','C','D'] * 5,
    'Region': ['East','West','North','South','East','West','North','South',
                'East','West','North','South','East','West','North','South',
                'East','West','North','South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John','Mary','Bob','Alice','John','Mary','Bob','Alice',
            'John','Mary','Bob','Alice','John','Mary','Bob','Alice',
            'John','Mary','Bob','Alice']
}

df = pd.DataFrame(data)
df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q'+df['Date'].dt.quarter.astype(str)

In [9]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    543     69   John  January      Q1
1  2023-01-02       B   West    185     85   Mary  January      Q1
2  2023-01-03       C  North    188     80    Bob  January      Q1
3  2023-01-04       D  South    896     61  Alice  January      Q1
4  2023-01-05       A   East    102     38   John  January      Q1
5  2023-01-06       B   West    464     30   Mary  January      Q1
6  2023-01-07       C  North    912     20    Bob  January      Q1
7  2023-01-08       D  South    610     40  Alice  January      Q1
8  2023-01-09       A   East    566     96   John  January      Q1
9  2023-01-10       B   West    373     96   Mary  January      Q1
10 2023-01-11       C  North    448     91    Bob  January      Q1
11 2023-01-12       D  South    645     32  Alice  January      Q1
12 2023-01-13       A   East    190     64   John  January      Q1
13 2023-01-14       B   West    384     15   Mary  January      Q1
14 2023-01-15       C  North    578     49    Bob  January      Q1
15 2023-01-16       D  South    258     91  Alice  January      Q1
16 2023-01-17       A   East    472     43   John  January      Q1
17 2023-01-18       B   West    193     85   Mary  January      Q1
18 2023-01-19       C  North    930     19    Bob  January      Q1
19 2023-01-20       D  South    246     96  Alice  January      Q1

In [12]:
pd.pivot_table(df,
               values = 'Sales',index='Region',columns ='Product',aggfunc='median')

Product      A      B      C      D
Region
East     472.0    NaN    NaN    NaN
North      NaN    NaN  578.0    NaN
South      NaN    NaN    NaN  610.0
West       NaN  373.0    NaN    NaN

In [13]:
pd.pivot_table(df,
               values=['Sales','Units'],index='Region',columns='Product')

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     374.6    NaN    NaN    NaN  62.0   NaN   NaN   NaN
North      NaN    NaN  611.2    NaN   NaN   NaN  51.8   NaN
South      NaN    NaN    NaN  531.0   NaN   NaN   NaN  64.0
West       NaN  319.8    NaN    NaN   NaN  62.2   NaN   NaN

### Cross Tabs

In [ ]:
pd.crosstab(df['Region'],df['Product']) #Counting

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0